### ISSUE TITLE
Add driver version attributes and dates for the last time they were tested.

### ISSUE THREAD

**Issue by rsbrost** [sandialabs/pyscan#108]

**Comment by rsbrost** [comment]
Could automatically implement this when the finalized test notebooks are run to update the base driver file.

**Comment by i-am-mounce** [comment]
Driver version, but not dates

**Comment by i-am-mounce** [comment]
Resolved by pull request 169

**Comment by i-am-mounce** [comment]
Resolved by pull request #169
