### ISSUE TITLE
Properties that are only get or set need to be availble in InstrumentDriver.add_device_property

### ISSUE THREAD

**Issue by ammounce** [sandialabs/pyscan#130]
Currently this is not possible, this also means that the dict keys of index_value, etc. could also not exist or specifically be None (for query only properties).

**Comment by mplilly4395** [comment]
read-only properties can be created by only using fget and doc in the property_definition which is the argument to ```Property()```.  If you try to set a read-only property, an AttributeError is raised with a message that "the property has no setter".

We can make a separate method for ```add_device_ro_property()```, or we can modify ```add_device_property``` to make a read-only property if the ```write_string``` key is missing from the settings dictionary.
