### ISSUE TITLE
ipykernel does not support python 3.12

### ISSUE THREAD

**Issue by plesiopterys** [sandialabs/pyscan#18]
might need to limit python version to 3.11 to use with conda/jupyter lab

**Comment by i-am-mounce** [comment]
I'm not seeing this issue with VSCode

**Comment by plesiopterys** [comment]
It's not an issue for VSCode, I don't think. You need to install ipykernel if you want to use a conda environment, then make the kernel accessible on Jupyter. However, if your python version is too high, you can't use ipykernel at present. That was the error. It won't affect anyone who isn't using conda envs and manually installs ipykernel.

**Comment by i-am-mounce** [comment]
I've confirmed this on mac now.

**Comment by rsbrost** [comment]
This issue may have been a non-issue, but Andy did find that for notebook to work more independently we want to install jupyter as a dependency for pyscan, and likely remove ipykernel (which is included in jupyter install). Testing this now.
