### ISSUE TITLE
hdf5 files do not save runinfo.measured

### ISSUE THREAD

**Issue by mplilly4395** [sandialabs/pyscan#189]
runinfo.measured is important for existing plot commands like PlotGenerator().  When you use the expt created in a jupyter notebook, the measured list is present.  If you use ps.load_experiment(), measured is an empty list.

In checking on this problem,
1. save_metadata() runs recursive_to_dict() and json.dumps()
2. recursive_to_dict() makes a dictionary with measured and the list is correct at this point
3. directly checking the hdf5 file runinfo attr: f.attrs['runinfo'], measured is an empty list.

**Comment by i-am-mounce** [comment]
Let's add this functionality to load_experiment

**Comment by mplilly4395** [comment]
reason: metadata is saved before the experiment begins.  The measured list is populated after the first data point, so it is empty when the metadata is saved.
