### ISSUE TITLE
04-example_average_scans.ipynb Cell 4: 

### ISSUE THREAD

**Issue by rsbrost** [sandialabs/pyscan#2]
NameError                                 Traceback (most recent call last)
Cell In[4], line 3
      1 # 0D data repeat
      2 runinfo = ps.RunInfo()
**----> 3 runinfo.loop0 = ps.AverageScan(10, dt=0.5)**
      5 runinfo.measure_function = generate_multiD_data
      7 # This is the only important difference

File ~\AppData\Local\anaconda3\Lib\site-packages\pyscan\measurement\scans.py:188, in AverageScan.__init__(self, n_average, dt)
    186 self.n = n_average
    187 self.nrange = range(self.n) 
**--> 188 self.scan_dict['average'] = list(nrange)**
    189 self.device_names = ['average']
    190 self.i = 0

NameError: name **'nrange' is not defined**

**Comment by plesiopterys** [comment]
fixed : should be self.nrange (references line 187)
