### ISSUE TITLE
Fix saving if files are made too quickly

### ISSUE THREAD

**Issue by i-am-mounce** [sandialabs/pyscan#20]
If files are made too quickly the file name is the same and an error is thrown

**Comment by i-am-mounce** [comment]
This happens when an experiment takes less than 1 second because pyscan trys to assign the same file name (accurate within 1 s) to a second experiment file.

**Comment by plesiopterys** [comment]
Hello!
I am currently out of office on parental leave until August 2024. 

For urgent matters, please text or call me at (310) 307 9272 or cc my contracter email address ***@***.***

Best regards,
Jasmine
