### ISSUE TITLE
Stanford 830 snap() bug

### ISSUE THREAD

**Issue by mplilly4395** [sandialabs/pyscan#217]
The SRS830 method snap() and snap_xy() requires a string of indices for arguments.  The string for the SCPI command has a bug when making the indices.  Integers cannot be joined into a string.

The change needed (on line 593) is to make the list of indices strings rather than integers:

currently: indicies = [sources.index(arg) + 1 for arg in args]
        
corrected: indicies = [str(sources.index(arg) + 1) for arg in args]
        
I can open a pull request with this change, but I know there is a branch specifically for the stanford 830.

**Comment by mplilly4395** [comment]
Jasmine, let me know if you want to include this in your branch, or if I should just submit a short fix for this.

**Comment by plesiopterys** [comment]
Hello!
I am currently out of office on parental leave until August 2024. 

For urgent matters, please text or call me at (310) 307 9272 or cc my contracter email address ***@***.***

Best regards,
Jasmine

**Comment by plesiopterys** [comment]
Sure I can implement this

**Comment by plesiopterys** [comment]
Nevermind, it looks like it's already implemented on the branch
