### ISSUE TITLE
Keithley 2400 no method to read the "measure" part of the SMU

### ISSUE THREAD

**Issue by mplilly4395** [sandialabs/pyscan#218]
The Keithley 2400 needs a read-only property for reading the measured value.  

":READ?" gets a list of data that includes voltage, current, resistance, etc.  

The driver needs a significant amount of work since there are so many options, but I think the most common usage (at least for transport experiments) is to set a voltage and read the current.  Given that mode, we need to be able to read the current.

**Comment by i-am-mounce** [comment]
Same as #41 closing.
