### ISSUE TITLE
Method of saving metadata needs to be JSON converter

### ISSUE THREAD

**Issue by rsbrost** [sandialabs/pyscan#28]

**Comment by plesiopterys** [comment]
current saving process is json.dumps (metasweep.py line 227, 228)

Need a NPencoder because error occurs if the runinfo contains any numpy type, e.g. int64.

**Comment by plesiopterys** [comment]
ERROR CODE:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[12], line 33
     30 runinfo.loop0 = ps.RepeatScan(1)
     32 expt=ps.Sweep(runinfo,devices)
---> 33 expt.run()

File C:\ProgramData\anaconda3\Lib\site-packages\pyscan\measurement\sweep.py:50, in Sweep.run(self)
     48 self.setup_instruments()
     49 # save instrument settings
---> 50 self.save_metadata()
     52 sleep(self.runinfo.initial_pause)
     54 self.get_time()

File C:\ProgramData\anaconda3\Lib\site-packages\pyscan\measurement\metasweep.py:227, in MetaSweep.save_metadata(self)
    224 data = recursive_to_dict(self.__dict__)
    226 with h5py.File(save_name, 'a') as f:
--> 227     f.attrs['runinfo'] = json.dumps(data['runinfo'])
    228     f.attrs['devices'] = json.dumps(data['devices'])

File C:\ProgramData\anaconda3\Lib\json\__init__.py:231, in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    226 # cached encoder
    227 if (not skipkeys and ensure_ascii and
    228     check_circular and allow_nan and
    229     cls is None and indent is None and separators is None and
    230     default is None and not sort_keys and not kw):
--> 231     return _default_encoder.encode(obj)
    232 if cls is None:
    233     cls = JSONEncoder

File C:\ProgramData\anaconda3\Lib\json\encoder.py:200, in JSONEncoder.encode(self, o)
    196         return encode_basestring(o)
    197 # This doesn't pass the iterator directly to ''.join() because the
    198 # exceptions aren't as detailed.  The list call should be roughly
    199 # equivalent to the PySequence_Fast that ''.join() would do.
--> 200 chunks = self.iterencode(o, _one_shot=True)
    201 if not isinstance(chunks, (list, tuple)):
    202     chunks = list(chunks)

File C:\ProgramData\anaconda3\Lib\json\encoder.py:258, in JSONEncoder.iterencode(self, o, _one_shot)
    253 else:
    254     _iterencode = _make_iterencode(
    255         markers, self.default, _encoder, self.indent, floatstr,
    256         self.key_separator, self.item_separator, self.sort_keys,
    257         self.skipkeys, _one_shot)
--> 258 return _iterencode(o, 0)

File C:\ProgramData\anaconda3\Lib\json\encoder.py:180, in JSONEncoder.default(self, o)
    161 def default(self, o):
    162     """Implement this method in a subclass such that it returns
    163     a serializable object for ``o``, or calls the base implementation
    164     (to raise a ``TypeError``).
   (...)
    178 
    179     """
--> 180     raise TypeError(f'Object of type {o.__class__.__name__} '
    181                     f'is not JSON serializable')

TypeError: Object of type int64 is not JSON serializable

**Comment by plesiopterys** [comment]
Example Numpy Encoder code:
https://stackoverflow.com/questions/50916422/python-typeerror-object-of-type-int64-is-not-json-serializable
