### ISSUE TITLE
Edit dict_values: user input should be key, machine string should be value

### ISSUE THREAD

**Issue by plesiopterys** [sandialabs/pyscan#59]

**Comment by plesiopterys** [comment]
Ryan and Jasmine completed this issue alongside tests. Tests are also working.

New return value is a list of all keys (user inputs) that match the machine's return value.

The dictionary consists of keys that are user inputs, and values that are sent and retrieved from the machine.

**Comment by rsbrost** [comment]
Closing issue now as it is resolved.

**Comment by rsbrost** [comment]
Reopening to link issue to pull request.
