### ISSUE TITLE
Make metsweep's save_metadata save a string summary of the experiment.

### ISSUE THREAD

**Issue by rsbrost** [sandialabs/pyscan#65]

**Comment by plesiopterys** [comment]
Includes:

type of scan in each loop + name of saved variable

names of data returned by measure_function & possibly n dims or dims

**Comment by rsbrost** [comment]
Maybe do this part as a function built into load experiment; however, more information needs to be preemptively saved, and one way or another we need an effective way for getting loaded experiments data readily and in a streamlined, easily understandable way.

**Comment by i-am-mounce** [comment]
This is not going to happen as written here.
